// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: DisplayArariboia-ILI9488

#ifndef _UI_COMP_MONITORPANEL_H
#define _UI_COMP_MONITORPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MonitorPanel
#define UI_COMP_MONITORPANEL_MONITORPANEL 0
#define _UI_COMP_MONITORPANEL_NUM 1
lv_obj_t * ui_MonitorPanel_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
