// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: DisplayArariboia-ILI9488

#ifndef _DISPLAYARARIBOIA_ILI9488_UI_H
#define _DISPLAYARARIBOIA_ILI9488_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void Blinking_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_RPM_Monitor_Container;
extern lv_obj_t * ui_RPM_R_Container;
extern lv_obj_t * ui_MonitorPanel;
extern lv_obj_t * ui_RPM_L;
extern lv_obj_t * ui_RPM_L_Text;
extern lv_obj_t * ui_MonitorPanel4;
extern lv_obj_t * ui_Current_RPM_L;
extern lv_obj_t * ui_Current_RPM_L_Text;
extern lv_obj_t * ui_RPM_Warning;
extern lv_obj_t * ui_RPM_L_Container;
extern lv_obj_t * ui_MonitorPanel1;
extern lv_obj_t * ui_RPM_R;
extern lv_obj_t * ui_MonitorPanel5;
extern lv_obj_t * ui_Current_RPM_R;
extern lv_obj_t * ui_RPM_R_Text;
extern lv_obj_t * ui_Current_RPM_R_Text;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Battery_and_Sola_Panel_Container;
extern lv_obj_t * ui_MonitorPanel2;
extern lv_obj_t * ui_Battery_Value;
extern lv_obj_t * ui_Battery_Text;
extern lv_obj_t * ui_MonitorPanel3;
extern lv_obj_t * ui_Solar_Panel_Value;
extern lv_obj_t * ui_Solar_Panel_Text;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_arariboialogopcn_png);    // assets\ArariboiaLogoPCN.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
